feat: Criando infraestrutura inicial com EF Core e migrations
LV-Enteprise/natal-jcc pull request #3
Opened 2020-10-22 02:14 UTC by viavn

**O que foi feito?**
- Alteração na estrutura de tabelas do sistema (docs/requisitos-banco.txt).
- Criação do projeto backend utilizando ASP .NET Core 3.1.
- Criação do banco de dados utilizando EF Core 3.1 e migrations.

2020-10-22 18:59 UTC, leonardoalves14 requested changes
Id                                   | uuid
(PK|FK) FamiliaId            | GUID	
Nome                            | character varying(255) not null
NomeParente                | VARCHAR(255)	
DataNascimento           | date                   not null
Batizado                        | boolean                not null
FazendoCatequese        | boolean                not null
ConcluiuCatequese       | boolean                not null
FazendoPerseveranca    | boolean                not null
ConcluiuPerseveranca   | boolean                not null
FazendoCrisma              | boolean                not null
ConcluiuCrisma             | boolean                not null
Observacao                   | text                       null
(PK|FK) FamiliaId            | uuid

Ao invés de fazendo e concluiu, não poderíamos colocar um campo situação ?
por exemplo: 
SituacaoCatequese      | varchar(10)
SituacaoPerse              | varchar(10) 
SituacaoCrisma            | varchar(10)   

Assim a gente grava tipo, concluido, em andamento ou não fez, o que voce acha?

2020-10-23 00:02 UTC, viavn commented
Não vou colocar esses campos como string, pois o usuário terá que digitar e isso é bem ruim, temos que criar algo que seja rápido pra ele preencher. Em relação a tabela, vou criar uma outra que terá o Id da criança e as opções booleanas.
Então possivelmente teremos um radio button no front para esse grupo de respostas.

2020-10-23 00:08 UTC, leonardoalves14 commented
Entendi, mas e se essas respostas vierem como padrão em um combobox, onde o usuário só define a situação? Bem radioButton também é uma melhor alternativa.

2020-10-23 03:44 UTC, leonardoalves14 approved these changes

2020-10-23 03:44 UTC, merged

2020-10-23 23:37 UTC, leonardoalves14 reviewed
okay